#index:
#    path: /
#    controller: App\Controller\DefaultController::index


api_user_register:
  path: /register
  controller: App\Controller\UserController::register
  methods: POST

api_user_login:
  path:       /login
  controller: App\Controller\UserController::login
  methods: POST